### ISSUE TITLE
        posevae_alignment_mae.pth 模型有下载吗

### ISSUE THREAD

**Issue by NingRC** [wanggang1987/fast_sadtalker#2]

**Comment by ardyli** [comment]
同问

**Comment by pigmeetsomebody** [comment]
同问

Traceback (most recent call last):
  File "inference.py", line 208, in <module>
    args.audio_to_coeff = Audio2Coeff(sadtalker_paths,  args.device)
  File "/home/qhzyy/zyy/fast_sadtalker/src/test_audio2coeff.py", line 55, in __init__
    self.audio2pose_model.netG.load_state_dict(torch.load("/data/AiModels/SadTalker-dev/checkpoints/posevae_alignment_mae.pth")) 
  File "/home/qhzyy/anaconda3/envs/sadtalker/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/qhzyy/anaconda3/envs/sadtalker/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/qhzyy/anaconda3/envs/sadtalker/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/data/AiModels/SadTalker-dev/checkpoints/posevae_alignment_mae.pth'

**Comment by tangbq** [comment]
同问
